/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.praticas.srestoque.clientedesktop;

import br.edu.ifpb.praticas.srestoque.exceptions.NenhumaEntradaRealizada;
import br.edu.ifpb.praticas.srestoque.regrasneogico.EntradaRN;
import br.edu.ifpb.praticas.srestoque.regrasneogico.EntradaRNimpl;
import br.edu.ifpb.praticas.srestoque.srestoqueentidades.Entrada;
import java.util.List;

/**
 *
 * @author vmvini
 */
public class PesquisaEntrada extends javax.swing.JInternalFrame {

    private EntradaRN entradaRN;
    
    
    /**
     * Creates new form PesquisaEntrada
     */
    public PesquisaEntrada() {
        entradaRN = new EntradaRNimpl();
        initComponents();
        
        try{
            initList();
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setClosable(true);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void initList() throws NenhumaEntradaRealizada{
        /*
        List<Produto> produtos = produtoRN.listarProdutos();
            Produto[] prs = produtos.toArray(new Produto[produtos.size()]);*/
        jList1.setModel(new javax.swing.AbstractListModel() {
            List<Entrada> entradas = entradaRN.listarEntradas();
            
            Entrada[] es = entradas.toArray(new Entrada[entradas.size()]);
            
            public int getSize() { return es.length; }
            public Object getElementAt(int i) { return es[i]; }
        });
        jScrollPane1.setViewportView(jList1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
