/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpb.praticas.srestoque.clientedesktop;

import br.edu.ifpb.praticas.srestoque.exceptions.NenhumProdutoCadastrado;
import br.edu.ifpb.praticas.srestoque.exceptions.NenhumaSaidaRealizada;
import br.edu.ifpb.praticas.srestoque.regrasneogico.ProdutoRN;
import br.edu.ifpb.praticas.srestoque.regrasneogico.ProdutoRNImpl;
import br.edu.ifpb.praticas.srestoque.regrasneogico.SaidaRN;
import br.edu.ifpb.praticas.srestoque.regrasneogico.SaidaRNImpl;
import br.edu.ifpb.praticas.srestoque.srestoqueentidades.Produto;
import br.edu.ifpb.praticas.srestoque.srestoqueentidades.Saida;
import java.util.List;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author vmvini
 */
public class Saidas extends javax.swing.JInternalFrame {

    
    private SaidaRN saidaRN;
    private ProdutoRN produtoRN;
    /**
     * Creates new form Saidas
     */
    public Saidas() {
        initComponents();
        saidaRN = new SaidaRNImpl();
        produtoRN = new ProdutoRNImpl();
        try{
            initList();
            
        }
        catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        quantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        erroMsg = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setClosable(true);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        quantity.setText("0");
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });

        jButton1.setText("Realizar Saida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(erroMsg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(erroMsg)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Saida saida = new Saida();
            saida.setQuantidade(Integer.parseInt( quantity.getText() ) );
            saida.setData(new Date());
            Produto p = (Produto) jList1.getSelectedValue();
            saida.setProduto(p);
            saidaRN.salvarSaida(saida);
            erroMsg.setText("");
            
            JOptionPane.showMessageDialog(null, "Saida realizada!");
            initList();
        }
        catch(RuntimeException e){
            erroMsg.setText(e.getMessage());
        }
        catch(Exception e){
            erroMsg.setText(e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    private void initList() throws NenhumProdutoCadastrado{
        
        jList1.setModel(new javax.swing.AbstractListModel() {
            
            List<Produto> produtos = produtoRN.listarProdutos();
            
            Produto[] es = produtos.toArray(new Produto[produtos.size()]);
            
            public int getSize() { return es.length; }
            public Object getElementAt(int i) { return es[i]; }
        });
        jScrollPane1.setViewportView(jList1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel erroMsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
